export const FETCHED_BOOK = 'FETCHED_BOOK';
export const REQUESTED_BOOK_FAILED = 'REQUESTED_BOOK_FAILED';
export const REQUESTED_BOOK_SUCCEEDED = 'REQUESTED_BOOK_SUCCEEDED';
export const REQUESTED_BOOK = 'REQUESTED_BOOK';